name: gradle test

on: 
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build-java:

    runs-on: ubuntu-latest
   
    steps:

    - uses: actions/checkout@v2

    - name: install java
      uses: actions/setup-java@1
      with:
        java-version: 1.8

    - name: gradle permissions
      run: chmod +x gradlew

    - name: build gradle
      run: ./gradlew build
